config/routes.rb
Rails.application.routes.draw do
  resources :cats, only: [:index, :show, :create, :update, :destroy, :new, :edit]
  root to: 'cats#index'
  resources :cat_rental_requests, only: [:new, :create, :update]
  post '/approve/:id', to: "cat_rental_requests#approve", as: :approve_cat
  post '/deny/:id', to: "cat_rental_requests#deny", as: :deny_cat
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :birth_date, :color, :name, :sex, presence: true
  validates :sex, inclusion: { in: ['F', 'M'] }


  has_many :requests,
    dependent: :destroy,
    class_name: :CatRentalRequest

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED) }

  validate :no_overlaping_aproved_requests

  def no_overlaping_aproved_requests
    if overlapping_approved_requests > 0 && self.status == "APPROVED"
      errors["Cat"] << "already checked out."
    end
  end

  belongs_to :cat

  def overlapping_requests
    data = CatRentalRequest.where(cat_id: self.cat_id)
      .where("start_date BETWEEN :start_date AND :end_date
        OR end_date BETWEEN :start_date AND :end_date
        OR :start_date BETWEEN start_date AND end_date",
        start_date: self.start_date, end_date: self.end_date)

    if self.id
      data.where("cat_rental_requests.id != ?", self.id)
    else
      data
    end
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: "APPROVED").count
  end

  def deny!
    self.status = "DENIED"
    self.save
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: "PENDING")
  end

  def approve!
    ActiveRecord::Base.transaction do
      self.status = "APPROVED" unless overlapping_approved_requests > 0
      self.save
      self.overlapping_pending_requests.destroy_all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController


  def create
    new_rental = CatRentalRequest.create(cat_rental_request_params)
    redirect_to cat_path(new_rental.cat_id)
  end

  def new
    @cats = Cat.all
    render :new
  end

  def approve
    rental = CatRentalRequest.find(params[:id])
    rental.approve!
    @cat = Cat.find(rental.cat_id)

    redirect_to cat_path(rental.cat_id)
  end

  def deny
    rental = CatRentalRequest.find(params[:id])
    rental.deny!
    @cat = Cat.find(rental.cat_id)

    redirect_to cat_path(rental.cat_id)
  end

  private

  def cat_rental_request_params
    params.require(:rental).permit(:cat_id, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    render :cats
  end

  def show
    @cat = Cat.find(params[:id])
    render :cat
  end

  def create
    new_cat = Cat.create(cat_params)

    redirect_to cat_path(new_cat)
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.update(cat_params)
    render :cat
  end

  def new
    @cat = Cat.new()
    render :new
  end

  private

  def cat_params
    params.require(:cat).permit(:sex, :color, :name, :birth_date, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_request_helper.rb
module CatRentalRequestHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <h2>Rent a Cat!</h2>

    <form action= <%= cat_rental_requests_url %> method="post">
      <label>
        Pick a cat:
        <select name="rental[cat_id]">
          <option value= <%= nil %>>(select cat)</option>
          <% @cats.each do |cat| %>
            <option value= <%= cat.id %> > <%= cat.name %> </option>
          <% end %>
        </select>
      </label>

      <br>
      <label>
        Start date:
        <input type="date" name="rental[start_date]">
      </label>

      <label>
        End date:
        <input type="date" name="rental[end_date]">
      </label>
      <button>Submit</button>
    </form>


  </body>
</html>

app/views/cats/_form.html.erb
    <form action= <%= cat.persisted? ? cat_url(cat.id) : cats_url %> method="POST" >
      <input type="hidden" name="_method" value= <%= cat.persisted? ? "PATCH" : "POST" %> >
      <label>Name
      <input type="text" name="cat[name]" value= <%= cat.name %>>
      </label>

      <label for="cat_gender">Gender</label>
      <select name="cat[sex]" id="cat_gender">
        <option value="nil">(select a gender)</option>
        <option value="M" <%= "selected" if cat.sex == "M" %>>Male</option>
        <option value="F" <%= "selected" if cat.sex == "F" %>>Female</option>
      </select>

      <br>

      <label for="cat_color">Color:</label>
      <% %w(Purple Black White Pokedots).each do |color| %>
        <%= color %><input type="radio" name="cat[color]" value=<%= color %> id="cat_color" <%= "checked" if color == cat.color %>>
      <% end %>

      <br>

      <label>Birth date
      <input type="date" name="cat[birth_date]" value= <%= cat.birth_date %>>
      </label>

      <br>

      <label>
        Description<br>
        <textarea name="cat[description]" rows="8" cols="50"><%= cat.description %></textarea>
      </label>
      <input type="submit" value="Submit">
    </form>

app/views/cats/cat.html.erb
<h2>
  <%=  @cat.name%>'s Info
</h2>
<table>
  <tr>
    <td>Color: </td>
    <td><%= @cat.color %></td>
  </tr>
  <tr>
    <td>Sex: </td>
    <td><%= @cat.sex %></td>
  </tr>
  <tr>
    <td>Birth date: </td>
    <td><%= @cat.birth_date %></td>
  </tr>
  <% unless @cat.description.nil? %>
  <tr>
    <td>Description: </td>
    <td><%= @cat.description %></td>
  </tr>
  <% end %>
</table><br>

<%= link_to("Edit cat information", edit_cat_url(@cat.id)) %><br>

<label><br>
  Pending requests:
  <ol>
    <% @cat.requests.order(:start_date).each do |request| %>
    <li>
      Start date: <%= request.start_date %>,
      End date: <%= request.end_date %>,
      Status: <%= request.status %>

      <% if request.status == "PENDING" %>
        <%= button_to( "Approve", approve_cat_path(request)) %>
        <%= button_to( "Deny", deny_cat_path(request)) %>
      <% end %>

    </li>
    <% end %>
  </ol>
</label>

app/views/cats/cats.html.erb
<h2>Rent a cat all ready</h2>
<ul>
  <% Cat.all.each do |cat| %>
  <li>
    <% @cat = cat %>
    name: <%=  cat.name%>
    color: <%=  cat.color%>
    sex: <%=  cat.sex%>

    <%= link_to("Individual cat page", cat_url(cat.id)) %>
  </li>
  <% end %>
</ul>

<%= link_to("Create new cat", new_cat_url) %><br>
<%= link_to("Request a cat rental", new_cat_rental_request_url) %>

app/views/cats/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New Cat Page</title>
  </head>
  <body>

    <h2>Update <%= @cat.name %></h2>
    <h3> Update your cats information: </h3>

    <%= render "form", cat: @cat %>

  </body>
</html>

app/views/cats/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New Cat Page</title>
  </head>
  <body>

    <h2> New Cat</h2>
    <h3> Enter your cats information: </h3>

    <%= render "form", cat: @cat %>


  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>